name=EEPROM24CXX
version=1.0.0
author=Alen KrishnaV.U
maintainer=Alen Krishna V.U <alenkrishnavu@gmail.com>
sentence=I2C EEPROM library for 24Cxx and 24CMxx EEPROM chips.
paragraph=Supports byte access, strings, buffers, datatypes, erase, fill, compare and write protection.
category=Data Storage
url=https://github.com/
architectures=*