name=EEPROM24CXX
version=1.0.0
author=Alen KrishnaV.U
maintainer=Alen Krishna V.U <alenkrishnavu@gmail.com>
sentence=Ultra-compact micro library for 24C02B I2C EEPROMs.
paragraph=Uses zero-overhead inline macros to keep compiled sketch sizes as small as possible.
category=Data Storage
url=
architectures=*
